server:
  port: 8287
spring:
  application:
    name: ogumaproject2
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//52.199.163.241:1521/FREEPDB1
    username: JPTCRSDBA1
    password: JPTCRSDBA1
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
