server:
  port: 8287
spring:
  application:
    name: ogumaproject2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.199.163.241:5432/oguma
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  jooq:
    sql-dialect: POSTGRES
    