/*
 * This file is generated by jOOQ.
 */
package jp.co.toshiba.ppocph.jooq.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import jp.co.toshiba.ppocph.jooq.Keys;
import jp.co.toshiba.ppocph.jooq.Public;
import jp.co.toshiba.ppocph.jooq.tables.records.CitiesRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cities extends TableImpl<CitiesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.cities</code>
     */
    public static final Cities CITIES = new Cities();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CitiesRecord> getRecordType() {
        return CitiesRecord.class;
    }

    /**
     * The column <code>public.cities.id</code>.
     */
    public final TableField<CitiesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.cities.name</code>.
     */
    public final TableField<CitiesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.cities.pronunciation</code>.
     */
    public final TableField<CitiesRecord, String> PRONUNCIATION = createField(DSL.name("pronunciation"), SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.cities.population</code>.
     */
    public final TableField<CitiesRecord, Long> POPULATION = createField(DSL.name("population"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.cities.city_flag</code>.
     */
    public final TableField<CitiesRecord, String> CITY_FLAG = createField(DSL.name("city_flag"), SQLDataType.VARCHAR(40), this, "");

    /**
     * The column <code>public.cities.district_id</code>.
     */
    public final TableField<CitiesRecord, Long> DISTRICT_ID = createField(DSL.name("district_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.cities.delete_flg</code>.
     */
    public final TableField<CitiesRecord, String> DELETE_FLG = createField(DSL.name("delete_flg"), SQLDataType.VARCHAR(8).nullable(false), this, "");

    private Cities(Name alias, Table<CitiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cities(Name alias, Table<CitiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.cities</code> table reference
     */
    public Cities(String alias) {
        this(DSL.name(alias), CITIES);
    }

    /**
     * Create an aliased <code>public.cities</code> table reference
     */
    public Cities(Name alias) {
        this(alias, CITIES);
    }

    /**
     * Create a <code>public.cities</code> table reference
     */
    public Cities() {
        this(DSL.name("cities"), null);
    }

    public <O extends Record> Cities(Table<O> child, ForeignKey<O, CitiesRecord> key) {
        super(child, key, CITIES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<CitiesRecord> getPrimaryKey() {
        return Keys.CITIES_PKEY;
    }

    @Override
    public List<ForeignKey<CitiesRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CITIES__FK_CITIES_DISTRICTS);
    }

    private transient Districts _districts;

    /**
     * Get the implicit join path to the <code>public.districts</code> table.
     */
    public Districts districts() {
        if (_districts == null)
            _districts = new Districts(this, Keys.CITIES__FK_CITIES_DISTRICTS);

        return _districts;
    }

    @Override
    public Cities as(String alias) {
        return new Cities(DSL.name(alias), this);
    }

    @Override
    public Cities as(Name alias) {
        return new Cities(alias, this);
    }

    @Override
    public Cities as(Table<?> alias) {
        return new Cities(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(String name) {
        return new Cities(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Name name) {
        return new Cities(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cities rename(Table<?> name) {
        return new Cities(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, String, Long, String, Long, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super String, ? super Long, ? super String, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super String, ? super Long, ? super String, ? super Long, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
